const fs = require('fs');

const data = `ALCORDO,BARBRA ANNE ,MEDINA
ALONZO-GAHISAN,THEA KRISTELLE ,VALLECER
ATILLO,NYLRAM ,SUAREZ
BANA-AY,RAMER ,MAGLUYAN
BARRIGA,LESLIE ANN ,TITO
BAZAN,QUEENY ,DAGONDON
BONTIA,GESSA MARIELLE ,CABALHUG
BRAGA,PHILIP JAY DELOS ,REYES
CABREJAS,BEN GELO ,SOTILLO
CARO,VINCENT SAMUEL ,BUNO
CASTRO,DEO ROBERT ,BODIONGAN
CEBEDO,ADRIAN TEOPISTO IV ,EVASCO
CHIPOCO,MEIL ,MAATA
DATOY, SHALON MAE ,CAMECIÑO
DEITA, JEAN CELESTE ,GALOS
DETABLAN, NIGEL YUL ,TACASTACAS
DOLLETON,ELLISSE ANNE ,CHICANO
DUEÑAS,NNEKA BRIGIT ,ALBENDA
ESTELLA,MARIO RAFAEL JR ,UY
GUANGCO,RANDY ,CARREON
INTERONE,DIANE CHRISTA ,BORRES
JALANDONI, KENT ,OJALES
JAO,CHRISTIAN ,MANGHAY
JIMENEZ,KIRBY ,MUTIA
LEE,AMBER ,UY
MACADAAG, ANAIRAH ,DIEGO
MAGAWAY,ANGEL MAY ,BANUA
MAHILUM,JHUN JOULES ,MONTEROLA
MANCOL,JULIUS  JR,DIGAL
MANGASI,KIMBERLY JOHN ,GEVERA
MANIGSACA,MELVINE LU ,OMITER
MENDOZA, RICO RAY ,TAGURAN
NAJEAL,RAVEN PATRICK ,HORTELANO
OLMEDO,RYAN ,PAGAPULAAN
ONG,GERALD MANUEL ,PALAMINE
PASCUAL,ELOISA ROSE ,YAP
PEPITO,CHARLINE ,SINARLO
POLITO,JOHANNES KEPLER ,SALUDSOD
ROA,JOZAR LEO ,MUTIA
ROA,NIKKI KARR MEI ,PALANGAN
ROSALES,FAUSTINO II ,PARAISO
SANTOS,RACHEL ,RODGRIGUEZ
SAQUIN,IANA STEPHANIE GAYLE ,PEÑAS
SAREÑOGON,JOHN LAURENCE ,BALCITA
SENCIO,SHEENDY MARIS ,TAMPAL
SOBONG, RICHETTE NYL ,TOLEDO
SOLIJON, KRUZETTE KHLOE ,LAO
TAGUPA,BEBIE QUEEN LUCELLE ,RAFALLO
VALENCIA,HARA KRISTEL ,GACERA
ALONTO,NUR-AHLIA ,GURO
BARBA,MARY ANN ,CABAHUG
BARLISAN,ALWINA MAY ,PAROJINOG
ENANORIA-ALMELOR,SHEENA ROSE ,PARCUTILO
ESTRADA, MARY ROSE ,MAGLANGIT
LAGO,ASRAFFY ,ARUMPAC
LAPPANG,MUHAMMAD VIRADJI ,PAULIN
MACARAMBON,ALIAH ,LANTO
MANTOS,EDWARD LAWRENCE ,SUACILLO
POLOYAPOY,MARK ANDREW ,SAYSON
SANTOS,ANGELO MICHAEL,
AMAN,JUDITH ,PARDILLO
ANCHES, HONEY CHRISTINE ,TULO
CADILE, VIRTUES BERNADETTE ,BALLER
CAGOCO,KAY SAHARA ,DAGONDON
CARPIO,CARYL JOYCE ,ABASA
CASIÑO,KRISTINE CLAIRE ,ESCORO
ENAD,ZAIRA ZUSANNE STEPHANIE ,ABELLANOSA
MANGATE,SITTIE FATHMA HAYANEE ,SINAL
PANDACA,NUR-EZZAH MESHAL ,MASORONG
PARRILLA,RIGEN ,CABAYLO
RABUYO,KRIZZA MAE ,JAUG
TOLEDO, FEB THERISSE ,LEDAMA
GURO, KHAYA SARAH ,PALOMO
ESCALERA, EVER MARY JOY ,SENECA
TIU, NOVEH SHENN ,JAMIS
MALATUS,SOHAYA ,BALINDONG
MAGLANGIT,ALEXIA PIE ,NACUA
ALBARICO,DULCE ANN ,YECYEC
ALFAFARA,JOYCE SUZZANE ,ANDRES
ARUELO,CAROLINE MARIE ,GOMOS
AVILA,ADRIAN ,TIMBANCAYA
BENITO,ABDULLAH ,EPPIE
CASIO, CATSTEVEN ,CORTES
DITINGKI,HASSIM ,GANIA
KOOK,MIN KI ,KIM
LARANJO, ROBE ,PARANGAN
LIMALIMA-SABROSO,MAUREEN FAYE ,YURANGO
MACAPIL,LOREDANA APRILE ,VALLES
MAGNO,FRENZ DALE ,LEGUA
MAPANDI,NIHAD ,RADIA
MEJARES,MYRIANE ,MAHINAY
MINTALAR,NICK JEROME ,DEIPARINE
PAGATPAT,KRISTINE ,KHU
PANOGAN,NICOLE PERPETUA SOCORRO ,REYES
PIANG,MOHAMMAD YUSOPH ,TAHA
RECAMADAS,BEN BASHIR ,LAURON
RESUELO,KURT JIMWELL ,GUIEB
RESULTAN,GERALD KIEN ,ALIZER
ROCAS,JENN ANGELA ,PAGENTE
SABROSO,LENBERGH ,OCULARES
SARIP,HANNAH SHARIF ,BASHIER
SUMALIPAO, SHEEN ,BUENO
TUAÑO,NORWIN ,GULANG
VALENCIA,DIANNE ROSE ,CAPUTOL
VARGAS,REYNA ANDREA ,TABANG
VEGA,CHARITY ,NAVARRO
MACASAMPAL, NORHANIFAH ,MAMUTUK
ADIL,MARYAM ,DOMINGO
AVENIDO,KRISTIAN ,TAGSIP
BAGUNDOL,PIERCE COLLIN ,MANABAT
BALCITA,JUNE REY DELA ,PEÑA
BOMEDIANO,ERIKA KRYSTEL ,LLANTOS
CANOY, NIKHOLI ,CURATIVO
COCA,RANNIE GIE ,KAAMIÑO
DAMILES,RUDY JIGGS ,TUANGGANG
DONASCO,FRANZ BRYAN ,OMEGA
FUENTES,CRYSHA FAITH ,CALLAO
GA,CHRISTIAN ROY ,LOPE
GUERRERO,HAMIL ROMULO ,BANCAYRIN
GUINAL,AMRESAH JANE ,BACO
HADJI ADATU,NAJMAH ,BALABAGAN
LAMPARAS,MARY FEL ,YAMUTA
LARUBIS,KRIZIA MYRRH ,DINGLASA
LLUCH,MARIA PATRICIA ISABEL ,TAN
LOMONGO,STEVANNEY GRACE ,TENEBROSO
MACADATO,MOHAMMAD FAISAL ,YUSOPH
MAGSAYO,PHILIP JOHN DE ,JUAN
MANAMPARAN,NAS-RAH ,SULTAN
MASINLOC,JOHANNA MICHELLE ,MARATAS
MICARANDAYO,TULIP JAN ,TACLOB
NANO,DARYL GAY ,CASOCOT
PACALNA, MOBARAC ,ABDULAZIS
PERTIMOS,NEIL ALDRIN ,MARTINEZ
PRANZA,MARK JONEM ,MAHINAY
SABAL,IAN DWIGHT ,PEPITO
SIDLAO,CHARISH MAE ,BORBON
TABANAO, AIANNE ED ,TAMSE
VALENCIA,BASIL ,SALIMBANGON
APAT, FAITH ANN ,JALOVA
BAGUIO,ALLOY TRIXIA ,MANZO
CARBONILLA,CARLA ME ,JOCSON
COLLANTES,MAYNARD JOHN JR ,JUROLAN
DIMASANGCAY, ZAHIRAH ,MANAMPARAN
POLOYAPOY, ASHLIEGH MAE ,SAYSON
TALIBONG,NATHANIEL ,VISMANOS
ABONG, DINO JAMES ,PAYOD
ADLAON,JESSA RICA ,GALLOGO
ALA,SITTIE ALMERAH ,ALI
ALONG,TIFFANY MAY ,CAILING
AMER,SITTIE RAYHANNAH H. ,BASIR
BALATERO, ANNA MAE ,PADULLON
BAYAWA,GIO VANNI ,LIMATOC
BAYLOSIS,SHERI LEI ,ANOBA
BESS,FLOURENCE RAY ,BULALHOG
BOLODO,ARLYN ,VILLANUEVA
BONAL,MALIKA JANAIRAH ,GAMPONG
CATALON,JUNE CLAUDITH ,GALLANERO
CEBEDO,ANDRE MITCHELL ,EVASCO
CEBEDO, JEZZEL JOICE ,LAGARE
DAMADA,AL-KHEEZAR ,MAULANA
DENOPOL,KEMBERLY ,ALVENDAR
EGAR-DE LEON,GEASREEN KAIRYLLE ,ALPAS
ESPANIO,RAPHAELA MARIE ,PANES
ESTEVES,MARCLE IRVING ,BAYOT
FERNANDEZ,ESTEPHANIE,
JADOL,XAIRA ,JAVIER
JIMENEZ,JOHN KIN ,MUTIA
LABE, ALEJA ,MARUHOM
LIBETARIO, SANDRA MAE ,TAN
MAINIT,SHAINA CHELSEY ,TIROL
MAULANA,YASHMIN ,CALALAGAN
MOBARAK,DENA ,USMAN
NAVARRA, GILLIAN FRANCES ,SUICO
NAVARRO,ROMMEL ENDRIAN ,BALBOA
OLEGARIO,DEEN PHILIP ,BAGOR
PALASAN,NIKKI ROSE ,CAJARTE
PANGGAGA, SITTIE AINA ,PANDI
QUIJARDO,GLORY MAE ,SIETE
REVELO,MICHELLE ,CABRERA
SINGH,C.J. ABTAR ,VILLANUEVA
SUMULONG,MARTIN CARMELO JR ,TRINIDAD
TIU,WILSON JOHN ,BALIDA
CAMID, SITTIE OMAYYAH ,MAYO
AGANTAL,SITTIE ,JAMILA
AGUSTERO ,JENO ,GIBELA
ALCALA,ANGELU ROSE ,MACABULOS
ALERIA,VERGIL ,ANDRIN
ARELLANO,JESSA EVE ,LUNGTAD
BALBIDO,CHERRYLYN ,GOMEZ
BATOON,JOHN ANGELOU ,MANANAONG
CAGAANAN,KIT CHRISTIAN ,OPADA
CEBEDO,RAYMOND EDWARD DE ,LEON
DELA CRUZ,PHILIP OMAR ,DIAZ
EJERCITO,HANNAH VYL ,TRIVILEGIO
EMPEYNADO,CHERYL KRIS ,SEDILLO
ERIGBUAGAS,JUSTIN CLARK ,SANCHEZ
ESTELLA,DANIKA MARIE ,CORONEL
ESTOISTA,HEIDI PAOLA ,BARRIGA
FIGUEROA,JENNIFER ,DIGAL
FRANCISCO,MARY ROSE ANNE ,VILLANUEVA
GINGCO,CRISTINE LYN ,SAREN
ILISAN,KEZEAH KEREN ,TAGALOGUIN
KATADA, MARIGOLD ,ALBURO
MADROÑAL,NATHANAEL JAMES ,GUAZON
MAGALLANES, RALD-ROMEO ,ABACAHIN
MIÑOZA,TRISTINE MAY ,EDAO
MURALLON,JUNESSA ,CANILLO
NANO,ALJANE ,BANGCAT
NG,TIFFANY JANE ,DELIMA
REALUBIT,AURA KEISHA ,CASTAÑOS
RHUDY,KARINA JO ,CAL
SALIG,IVY ,BABANTO
SARIGUMBA,MONIQUE ,BAGALOYOS
TAHIL,SAMIR ,UY
TRINIDAD,THERESE KATE ,ABAMONGA
VILLANUEVA,GRAYVIMIN ,FIGUERAS`;

const lines = data.split('\n');
const doctors = lines.map(line => {
  const parts = line.split(',');
  if (parts.length >= 2) {
    const lastName = parts[0].trim();
    const firstName = parts[1].trim();
    let mid = parts.length > 2 ? parts[2].trim() : '';
    
    // DR. FIRSTNAME MI. LASTNAME
    // Let's format as LASTNAME, FIRSTNAME MI.
    const name = `DR. ${firstName} ${mid ? mid + ' ' : ''}${lastName}`;
    // Replace double spaces with single
    return name.replace(/\s+/g, ' ');
  }
  return null;
}).filter(d => !!d).sort();

const content = `export const DOCTORS = ${JSON.stringify(doctors, null, 2)};`;
fs.writeFileSync('src/lib/doctors.ts', content);
